name: Configlet

on:
  push:
  pull_request:

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Fetch configlet
      run: ./bin/fetch-configlet

    - name: Lint
      run: ./bin/configlet lint .
