name: Configlet CI

on:
  push:
  pull_request:

jobs:
  configlet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675 # 2.3.3

    - name: Fetch configlet
      uses: exercism/github-actions/configlet-ci@remove-extras
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configlet Linter
      run: configlet lint .
